#!/bin/sh
# Regenerate Formula/openroutine.rb for a released version.
#
# Wholesale regeneration, not sed-patching: the template below is the single
# source of truth for the formula's shape, so a hand-edit that drifts from it
# cannot survive the next release. Run from the repo root.
#
#   .github/scripts/update-formula.sh 1.0.5 artifacts
#
# where the second argument is a directory holding the four release tarballs.
set -eu

version="${1:?usage: update-formula.sh VERSION TARBALL_DIR}"
dir="${2:?usage: update-formula.sh VERSION TARBALL_DIR}"

# sha256sum on Linux, shasum on macOS — this runs in CI and by hand.
sha() {
  file="$dir/openroutine-v$version-$1.tar.gz"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | cut -d' ' -f1
  else
    shasum -a 256 "$file" | cut -d' ' -f1
  fi
}

base="https://github.com/soulmachine/openroutine/releases/download/v$version"

cat > Formula/openroutine.rb <<EOF
# Generated by .github/scripts/update-formula.sh — do not edit by hand.
#
# A prebuilt-binary formula: the release already builds these four targets, so
# brew unpacks the same tarball npm downloads rather than compiling anything.
class Openroutine < Formula
  desc "Your AI agents' crontab, as markdown"
  homepage "https://openroutine.dev"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/openroutine-v$version-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$base/openroutine-v$version-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$base/openroutine-v$version-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$(sha aarch64-unknown-linux-gnu)"
    end
    on_intel do
      url "$base/openroutine-v$version-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-gnu)"
    end
  end

  def install
    bin.install "openroutine"
  end

  test do
    assert_match "openroutine #{version}", shell_output("#{bin}/openroutine --version")
  end
end
EOF
