# Generated by .github/scripts/update-formula.sh — do not edit by hand.
#
# A prebuilt-binary formula: the release already builds these four targets, so
# brew unpacks the same tarball npm downloads rather than compiling anything.
class Openroutine < Formula
  desc "Your AI agents' crontab, as markdown"
  homepage "https://openroutine.dev"
  version "1.0.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.5/openroutine-v1.0.5-aarch64-apple-darwin.tar.gz"
      sha256 "694bdff13c415b09de4e7f39157768e485fbd0ae470b179a17717a6b9c2b7f8e"
    end
    on_intel do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.5/openroutine-v1.0.5-x86_64-apple-darwin.tar.gz"
      sha256 "31fcc38a6eeaf2b7f31a98e6ae359d85f28fdb4bd0dcbea3eb84ba789408c91a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.5/openroutine-v1.0.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9e732fe1654282d3aabb4f7e4954992dbadf19db10efdcddcf8b8a6b3f69df58"
    end
    on_intel do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.5/openroutine-v1.0.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "927449e34f83a530f94fa177c39fd0ae2ea202686af770fa5cbda17932cca2d0"
    end
  end

  def install
    bin.install "openroutine"
  end

  test do
    assert_match "openroutine #{version}", shell_output("#{bin}/openroutine --version")
    # --version alone passes on a binary whose config layer is broken, so walk
    # the write-then-read path too. --config is global, and without it these
    # would touch the real config.
    system bin/"openroutine", "--config", testpath/"config.toml", "init"
    assert_match "No tasks found",
                 shell_output("#{bin}/openroutine --config #{testpath}/config.toml list")
  end
end
