# Generated by .github/scripts/update-formula.sh — do not edit by hand.
#
# A prebuilt-binary formula: the release already builds these four targets, so
# brew unpacks the same tarball npm downloads rather than compiling anything.
class Openroutine < Formula
  desc "Your AI agents' crontab, as markdown"
  homepage "https://openroutine.dev"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.4/openroutine-v1.0.4-aarch64-apple-darwin.tar.gz"
      sha256 "7fb6d0d0c8467747d63d28522b1a497dd7f38e4b11388120b1ed196e4fc1548f"
    end
    on_intel do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.4/openroutine-v1.0.4-x86_64-apple-darwin.tar.gz"
      sha256 "563fbcba273b6ac725c7323a55f147938421835aa6398879cbf264c193f4558f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.4/openroutine-v1.0.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "88ad3f5c90600222e519bc50c039559f43c5733b52a3010df6163b18cc9ee95c"
    end
    on_intel do
      url "https://github.com/soulmachine/openroutine/releases/download/v1.0.4/openroutine-v1.0.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "69bc43d3cb76e47156f44e3219fdfe8689a9394b2ec51fb8f5653fa231335a5f"
    end
  end

  def install
    bin.install "openroutine"
  end

  test do
    assert_match "openroutine #{version}", shell_output("#{bin}/openroutine --version")
  end
end
